# Generated by Django 5.0.6 on 2024-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_img',
            field=models.ImageField(null=True, upload_to='avatar_images/'),
        ),
    ]
