# Generated by Django 5.0.7 on 2024-09-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_customuser_two_factor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='base32_secret',
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_email',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
