# Generated by Django 5.0.7 on 2024-09-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_customuser_base32_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='base32_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
