# Generated by Django 5.0.7 on 2024-09-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_customuser_avatar_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='base32_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
