# Generated by Django 5.0.7 on 2024-11-13 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pong', '0008_remove_pongmatch_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_paddle_bounces', models.IntegerField(default=0)),
                ('p2_paddle_bounces', models.IntegerField(default=0)),
                ('p1_points_lost_by_wall_hit', models.IntegerField(default=0)),
                ('p2_points_lost_by_wall_hit', models.IntegerField(default=0)),
                ('p1_points_lost_by_wrong_color', models.IntegerField(default=0)),
                ('p2_points_lost_by_wrong_color', models.IntegerField(default=0)),
                ('p1_color_switches', models.IntegerField(default=0)),
                ('p2_color_switches', models.IntegerField(default=0)),
                ('match_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pong_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='pong.pongmatch')),
            ],
            options={
                'verbose_name': 'Match Statistics',
                'verbose_name_plural': 'Match Statistics',
            },
        ),
    ]
