# Generated by Django 5.0.7 on 2024-11-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='loser_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
