# Generated by Django 5.0.7 on 2024-09-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosted', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('player1_uuid', models.BigIntegerField()),
                ('player2_uuid', models.BigIntegerField()),
            ],
        ),
    ]
