# Generated by Django 5.0.7 on 2024-10-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pongmatch',
            old_name='hosted',
            new_name='aborted',
        ),
    ]
