# Generated by Django 5.0.7 on 2024-10-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_rename_hosted_pongmatch_aborted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongmatch',
            name='p1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pongmatch',
            name='p2_score',
            field=models.IntegerField(default=0),
        ),
    ]
