# Generated by Django 5.0.7 on 2024-10-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_pongmatch_p1_score_pongmatch_p2_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongmatch',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
