# Generated by Django 5.0.7 on 2024-11-04 14:07

from django.db import migrations

def convert_id_to_key(apps, schema_editor):
    PongMatch = apps.get_model('pong', 'PongMatch')
    CustomUser = apps.get_model('user_management', 'CustomUser')

    for match in PongMatch.objects.all():
        try:
            p1 = CustomUser.objects.get(id=match.player1_uuid)
            match.player1 = p1

        except Exception:
            match.player1 = None

        try:
            p2 = CustomUser.objects.get(id=match.player2_uuid)
            match.player2 = p2

        except Exception:
            match.player2 = None

        match.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_pongmatch_player1_pongmatch_player2_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_id_to_key,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
