# Generated by Django 5.0.7 on 2024-11-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_pongmatch_player1_pongmatch_player2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pongmatch',
            name='player1_uuid',
        ),
        migrations.RemoveField(
            model_name='pongmatch',
            name='player2_uuid',
        ),
    ]
