# Generated by Django 5.0.7 on 2024-11-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_remove_pongmatch_player1_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pongmatch',
            name='type',
            field=models.CharField(default='local_classic', max_length=100),
        ),
    ]
