# Generated by Django 5.0.7 on 2024-11-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_pongmatch_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pongmatch',
            name='local',
        ),
    ]
