# Generated by Django 5.0.7 on 2024-11-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0009_pongmatch_date_joined'),
        ('pong', '0009_pongmatch_tournament'),
    ]

    operations = [
    ]
