# Generated by Django 5.0.6 on 2024-10-04 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='user',
            new_name='current_user',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='blocked_friends',
            field=models.ManyToManyField(blank=True, related_name='blocked_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
